### PR TITLE
Minor fix to allow script to compile 1.13.1 under VS2017

### PR DESCRIPTION
**Pull request by asbe**
A small patch is needed in the source file op_kernel.h to allow the script to sucessfully compile  v1.13.1 under Visual Studio 2017, see https://github.com/tensorflow/tensorflow/pull/25943

### CODE REVIEW

**Comment by guikarist** [comment]
Is it better to use [the Tensorflow's commit](https://github.com/tensorflow/tensorflow/commit/ec727016282383aacf9d26386b01f6bdbd65b14b) as a patch?

**Comment by asbe** [comment]
Maybe - the difference is only slight. And the script looks cleaner with a cherry-pick instead of shipping a patch. Will test when I have the time.

**Comment by guikarist** [comment]
Waiting for your testing!

**Comment by guikarist** [comment]
@asbe Hey, have you already tested?

**Comment by asbe** [comment]
Sorry - been extremely busy. Assuming that Invoke-WebRequest behaves like curl the following addition to script should work. Sorry I don't speak Powershell: 

`} elseif ($buildVersion -eq "v1.13.1") {
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest https://github.com/tensorflow/tensorflow/commit/ec727016282383aacf9d26386b01f6bdbd65b14b.patch | git apply -v --ignore-space-change --ignore-white
}`

Have changed the script and will test a clean rebuild now.

**Comment by guikarist** [comment]
> Sorry - been extremely busy.

That's fine. I didn't mean to push you. 😉

You made duplicate codes in `$BuildCppAPI` which should be run outside once. So I removed them. Have a check, if nothing is wrong, this PR is ready to merge.

**Pull request merged**
